[browser]
gatherUsageStats = false

[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base = 

# Primary accent color for interactive elements.
primaryColor = "#875C5C"

# Background color for the main content area.
backgroundColor = "#ece6e3"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#cebfb6"

# Color used for almost all text.
textColor = "#000000" 

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"
